### PR TITLE
Environment/moving platform

### PR DESCRIPTION
**Pull request by DerrickPikachu**
This PR just implement a moving platform.
I trying to make player, zako and magic fort can stay on the platform.
Please check.

### CODE REVIEW

**Comment by MinecraftDawn** [comment]
If the speed of the moving platform is greater than 4 and it changes direction while the player is standing on it, the player will bounce upwards

**Comment by MinecraftDawn** [comment]
The player's relative speed to the platform differs depending on their movement direction is the same as or opposite to the platform's direction.

**Comment by DerrickPikachu** [comment]
> If the speed of the moving platform is greater than 4 and it changes direction while the player is standing on it, the player will bounce upwards

**Comment by DerrickPikachu** [comment]
> The player's relative speed to the platform differs depending on their movement direction is the same as or opposite to the platform's direction.

I think it is ok, because when player is standing on the platform, the moving speed of the player should be the relative velocity with the platform. If you have more concern, let's discuss in the meeting.

**Pull request merged**
